/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package A_Uppgift;

/**
 * @author Vladislav Zhuravskii
 * 09.03.2025
 */


import java.awt.Color;

public class A_Uppgift extends javax.swing.JFrame {
    
    /**
    *      *** Variables ***
    */
    
    
    char playerChoice; // Initial choice of A B or C
    char hostOpened;  // curtain host opened revealing the goat
    char finalChoice;    // final choice after suggestion to change
    // Custom button switches so disabled curtain looks the same
    boolean btnCurtainAEnabled = true;
    boolean btnCurtainBEnabled = true;
    boolean btnCurtainCEnabled = true;
    // Load icons for car and goat reveal animations
    javax.swing.ImageIcon carGif = new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/CarReveal.gif"));
    javax.swing.ImageIcon goatGif = new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/GoatReveal.gif"));
    

    /**
     * Creates new form A_Uppgift
     */
    public A_Uppgift() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFirstChoice = new javax.swing.ButtonGroup();
        btnGroupFinalChoice = new javax.swing.ButtonGroup();
        lblGameTitle = new javax.swing.JLabel();
        tbpMainTabs = new javax.swing.JTabbedPane();
        pnlGame = new javax.swing.JPanel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        txpHostText = new javax.swing.JTextPane();
        lblGameHost = new javax.swing.JLabel();
        lblPlayerChoiceA = new javax.swing.JLabel();
        lblPlayerChoiceB = new javax.swing.JLabel();
        lblPlayerChoiceC = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        btnCurtainA = new javax.swing.JButton();
        btnCurtainB = new javax.swing.JButton();
        btnCurtainC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResults = new javax.swing.JTextArea();
        lblResults = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        pnlSimulation = new javax.swing.JPanel();
        lblIntroduction = new javax.swing.JLabel();
        pnlFirstChoice = new javax.swing.JPanel();
        lblFirstChoice = new javax.swing.JLabel();
        rbtnFirstChoiceA = new javax.swing.JRadioButton();
        rbtnFirstChoiceB = new javax.swing.JRadioButton();
        rbtnFirstChoiceC = new javax.swing.JRadioButton();
        rbtnFirstChoiceRandom = new javax.swing.JRadioButton();
        pnlFinalChoice = new javax.swing.JPanel();
        lblFinalChoice = new javax.swing.JLabel();
        rbtnFinalChoiceYes = new javax.swing.JRadioButton();
        rbtnFinalChoiceNo = new javax.swing.JRadioButton();
        rbtnFinalChoiceRandom = new javax.swing.JRadioButton();
        pnlSimulationsNumber = new javax.swing.JPanel();
        lblSimulationsNumber = new javax.swing.JLabel();
        txfSimulationsNumber = new javax.swing.JTextField();
        btnStartSimulation = new javax.swing.JButton();
        pgbProgress = new javax.swing.JProgressBar();
        scrSimulationResults = new javax.swing.JScrollPane();
        txpSimulationResults = new javax.swing.JTextPane();
        lblSimulationResults = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGameTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGameTitle.setText("Monty Hall-problemet");

        tbpMainTabs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnlGame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlGame.setPreferredSize(new java.awt.Dimension(400, 200));
        pnlGame.setLayout(null);

        btnYes.setText("Ja!");
        btnYes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnYes.setFocusable(false);
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        pnlGame.add(btnYes);
        btnYes.setBounds(400, 270, 72, 23);
        btnYes.setVisible(false);

        btnNo.setText("Nej!");
        btnNo.setFocusable(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        pnlGame.add(btnNo);
        btnNo.setBounds(480, 270, 72, 23);
        btnNo.setVisible(false);

        txpHostText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txpHostText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txpHostText.setText("Det finns tre gardiner - bakom en finns en bil, och bakom de två andra finns getter.");
        txpHostText.setFocusable(false);
        txpHostText.setMargin(new java.awt.Insets(6, 6, 6, 6));
        txpHostText.setPreferredSize(new java.awt.Dimension(180, 140));
        pnlGame.add(txpHostText);
        txpHostText.setBounds(390, 170, 180, 140);
        txpHostText.setContentType("text/html");
        txpHostText.setText("<html>Det finns tre gardiner - bakom en finns en bil, och bakom de två andra finns getter. Välj den gardin som du vill öppna genom att klicka på bilden.");

        lblGameHost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/Host.png"))); // NOI18N
        lblGameHost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblGameHost.setPreferredSize(new java.awt.Dimension(200, 300));
        pnlGame.add(lblGameHost);
        lblGameHost.setBounds(380, 20, 200, 300);

        lblPlayerChoiceA.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlGame.add(lblPlayerChoiceA);
        lblPlayerChoiceA.setBounds(75, 125, 40, 40);

        lblPlayerChoiceB.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlGame.add(lblPlayerChoiceB);
        lblPlayerChoiceB.setBounds(195, 125, 40, 40);

        lblPlayerChoiceC.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlGame.add(lblPlayerChoiceC);
        lblPlayerChoiceC.setBounds(315, 125, 40, 40);

        lblA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/A.png"))); // NOI18N
        pnlGame.add(lblA);
        lblA.setBounds(60, 20, 25, 25);

        lblB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/B.png"))); // NOI18N
        pnlGame.add(lblB);
        lblB.setBounds(180, 20, 25, 25);

        lblC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/C.png"))); // NOI18N
        pnlGame.add(lblC);
        lblC.setBounds(300, 20, 25, 25);

        btnCurtainA.setBackground(new java.awt.Color(255, 255, 255));
        btnCurtainA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png"))); // NOI18N
        btnCurtainA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCurtainA.setPreferredSize(new java.awt.Dimension(100, 150));
        btnCurtainA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurtainAActionPerformed(evt);
            }
        });
        pnlGame.add(btnCurtainA);
        btnCurtainA.setBounds(20, 20, 100, 150);

        btnCurtainB.setBackground(new java.awt.Color(255, 255, 255));
        btnCurtainB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png"))); // NOI18N
        btnCurtainB.setPreferredSize(new java.awt.Dimension(100, 150));
        btnCurtainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurtainBActionPerformed(evt);
            }
        });
        pnlGame.add(btnCurtainB);
        btnCurtainB.setBounds(140, 20, 100, 150);

        btnCurtainC.setBackground(new java.awt.Color(255, 255, 255));
        btnCurtainC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png"))); // NOI18N
        btnCurtainC.setPreferredSize(new java.awt.Dimension(100, 150));
        btnCurtainC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurtainCActionPerformed(evt);
            }
        });
        pnlGame.add(btnCurtainC);
        btnCurtainC.setBounds(260, 20, 100, 150);

        txaResults.setColumns(20);
        txaResults.setRows(5);
        txaResults.setFocusable(false);
        jScrollPane1.setViewportView(txaResults);

        pnlGame.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 340, 110);

        lblResults.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResults.setText("Mina resultat:");
        pnlGame.add(lblResults);
        lblResults.setBounds(20, 180, 80, 16);

        btnPlayAgain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlayAgain.setText("Spela igen!");
        btnPlayAgain.setEnabled(false);
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });
        pnlGame.add(btnPlayAgain);
        btnPlayAgain.setBounds(20, 330, 105, 27);

        tbpMainTabs.addTab("Spelet", pnlGame);

        lblIntroduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIntroduction.setText("<html>Här kan du simulera olika strategier för spelarbeteende i spelet över många försök och se vilken strategi som ger bättre resultat!");

        pnlFirstChoice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFirstChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirstChoice.setText("Första valet");

        btnGroupFirstChoice.add(rbtnFirstChoiceA);
        rbtnFirstChoiceA.setText("A");
        rbtnFirstChoiceA.setFocusable(false);

        btnGroupFirstChoice.add(rbtnFirstChoiceB);
        rbtnFirstChoiceB.setText("B");

        btnGroupFirstChoice.add(rbtnFirstChoiceC);
        rbtnFirstChoiceC.setText("C");

        btnGroupFirstChoice.add(rbtnFirstChoiceRandom);
        rbtnFirstChoiceRandom.setSelected(true);
        rbtnFirstChoiceRandom.setText("Slumpmässig");

        javax.swing.GroupLayout pnlFirstChoiceLayout = new javax.swing.GroupLayout(pnlFirstChoice);
        pnlFirstChoice.setLayout(pnlFirstChoiceLayout);
        pnlFirstChoiceLayout.setHorizontalGroup(
            pnlFirstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFirstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstChoice)
                    .addComponent(rbtnFirstChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnFirstChoiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnFirstChoiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnFirstChoiceRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFirstChoiceLayout.setVerticalGroup(
            pnlFirstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFirstChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFirstChoiceA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFirstChoiceB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFirstChoiceC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFirstChoiceRandom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFinalChoice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFinalChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFinalChoice.setText("Ändra valet?");

        btnGroupFinalChoice.add(rbtnFinalChoiceYes);
        rbtnFinalChoiceYes.setText("Ja");

        btnGroupFinalChoice.add(rbtnFinalChoiceNo);
        rbtnFinalChoiceNo.setText("Nej");

        btnGroupFinalChoice.add(rbtnFinalChoiceRandom);
        rbtnFinalChoiceRandom.setSelected(true);
        rbtnFinalChoiceRandom.setText("Slumpmässig");

        javax.swing.GroupLayout pnlFinalChoiceLayout = new javax.swing.GroupLayout(pnlFinalChoice);
        pnlFinalChoice.setLayout(pnlFinalChoiceLayout);
        pnlFinalChoiceLayout.setHorizontalGroup(
            pnlFinalChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinalChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinalChoice)
                    .addComponent(rbtnFinalChoiceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnFinalChoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnFinalChoiceRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFinalChoiceLayout.setVerticalGroup(
            pnlFinalChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinalChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFinalChoiceYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFinalChoiceNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFinalChoiceRandom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSimulationsNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSimulationsNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSimulationsNumber.setText("<html> Antal<br>simuleringar<br>1-99999");

        txfSimulationsNumber.setText("1000");

        javax.swing.GroupLayout pnlSimulationsNumberLayout = new javax.swing.GroupLayout(pnlSimulationsNumber);
        pnlSimulationsNumber.setLayout(pnlSimulationsNumberLayout);
        pnlSimulationsNumberLayout.setHorizontalGroup(
            pnlSimulationsNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimulationsNumberLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txfSimulationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSimulationsNumberLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblSimulationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSimulationsNumberLayout.setVerticalGroup(
            pnlSimulationsNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimulationsNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSimulationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfSimulationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ((javax.swing.text.AbstractDocument) txfSimulationsNumber.getDocument()).setDocumentFilter(new NumericDocumentFilter(5));

        btnStartSimulation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStartSimulation.setText("Simulera!");
        btnStartSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSimulationActionPerformed(evt);
            }
        });

        pgbProgress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pgbProgress.setStringPainted(true);

        scrSimulationResults.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txpSimulationResults.setFocusable(false);
        scrSimulationResults.setViewportView(txpSimulationResults);

        lblSimulationResults.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSimulationResults.setText("Resultaten av simuleringarna:");

        javax.swing.GroupLayout pnlSimulationLayout = new javax.swing.GroupLayout(pnlSimulation);
        pnlSimulation.setLayout(pnlSimulationLayout);
        pnlSimulationLayout.setHorizontalGroup(
            pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimulationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIntroduction, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSimulationLayout.createSequentialGroup()
                        .addComponent(btnStartSimulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(pnlFirstChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlFinalChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlSimulationsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrSimulationResults)
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(lblSimulationResults)
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSimulationLayout.setVerticalGroup(
            pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimulationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(lblSimulationResults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrSimulationResults, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(lblIntroduction, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlFirstChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFinalChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSimulationsNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStartSimulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        lblIntroduction.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createEtchedBorder(),   // Outer border
            new javax.swing.border.EmptyBorder(10, 20, 10, 10)       // Inner padding (Top, Left, Bottom, Right)
        ));

        tbpMainTabs.addTab("Simuleringen", pnlSimulation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(lblGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tbpMainTabs)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblGameTitle)
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbpMainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Randomly decide the position of the car
    char carPosition = getCarPosition();
    
    // When player clicks on one of the curtains, his choise is set,
    // curtains are diabled and first part of the game starts
    private void btnCurtainAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtainAActionPerformed
        if (btnCurtainAEnabled) {
            playerChoice = 'A';
            hostOpened = firstPlayerChoice(playerChoice);
            disableCurtains();
        }
    }//GEN-LAST:event_btnCurtainAActionPerformed

    private void btnCurtainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtainBActionPerformed
        if (btnCurtainBEnabled) {
            playerChoice = 'B';
            hostOpened = firstPlayerChoice(playerChoice);
            disableCurtains();
        }
    }//GEN-LAST:event_btnCurtainBActionPerformed

    private void btnCurtainCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtainCActionPerformed
        if (btnCurtainCEnabled) {
            playerChoice = 'C';
            hostOpened = firstPlayerChoice(playerChoice);
            disableCurtains();
        }
    }//GEN-LAST:event_btnCurtainCActionPerformed

    // Second player choise and the second part of the game
    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        secondPlayerChoice("Yes");
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        secondPlayerChoice("No");
    }//GEN-LAST:event_btnNoActionPerformed

    // Game reset button
    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        
        // disable the play again button
        btnPlayAgain.setEnabled(false);
        
        // reset curtains
        btnCurtainAEnabled = true;
        btnCurtainA.setFocusable(true);
        btnCurtainA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png")));
        btnCurtainBEnabled = true;
        btnCurtainB.setFocusable(true);
        btnCurtainB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png")));
        btnCurtainCEnabled = true;
        btnCurtainC.setFocusable(true);
        btnCurtainC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/ClosedCurtain.png")));
        
        // reset choice arrow
        lblPlayerChoiceA.setIcon(null);
        lblPlayerChoiceB.setIcon(null);
        lblPlayerChoiceC.setIcon(null);
        
        // reset yes/no buttons
        btnYes.setBorder(javax.swing.UIManager.getBorder("Button.border"));
        btnYes.setVisible(false);
        btnYes.setFocusable(false);
        btnYes.setEnabled(true);
        btnNo.setBorder(javax.swing.UIManager.getBorder("Button.border"));
        btnNo.setVisible(false);
        btnNo.setFocusable(false);
        btnNo.setEnabled(true);
        
        // reset host text
        txpHostText.setText("<html>Det finns tre gardiner - bakom en finns en bil, och bakom de två andra finns getter. Välj den gardin som du vill öppna genom att klicka på bilden.");
        
        // set new random position for the car
        carPosition = getCarPosition();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    // Start simulation (all code for simulation is here)
    private void btnStartSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSimulationActionPerformed
        
        // disable the button and controls while simulation is in progress
        btnStartSimulation.setEnabled(false);
        setPanelEnabled(pnlFirstChoice, false);
        setPanelEnabled(pnlFinalChoice, false);
        setPanelEnabled(pnlSimulationsNumber, false);
        
        // load number of simulations required by  user
        int simulationsNumber = Integer.valueOf(txfSimulationsNumber.getText());
        // Replace 0 with 1
        if (simulationsNumber == 0) {
            simulationsNumber = 1;
            txfSimulationsNumber.setText("1");
        }
        
        // Counter for how many simulations ended with player winning the car
        int playerWonCar = 0;
        
        // Simulation loop
        for (int i = 1; i <= simulationsNumber; i++) {
            
            // Determine car position
            char simulatedCarPosition = getCarPosition();
            
            // Determine first player choice
            char simulatedPlayerChoice;
            {
            if  (rbtnFirstChoiceA.isSelected())
                simulatedPlayerChoice = 'A';
            else if (rbtnFirstChoiceB.isSelected()) 
                simulatedPlayerChoice = 'B';
            else if (rbtnFirstChoiceC.isSelected()) 
                simulatedPlayerChoice = 'C';
            else
                simulatedPlayerChoice = getCarPosition();
            }
      
             // Determine which curtain the host will open
            char simulatedHostOpens = findGoat(simulatedPlayerChoice, simulatedCarPosition);
            
            // Determine if the player will change the choice
            char willPlayerChange;
            {
            if  (rbtnFinalChoiceYes.isSelected()) {
                willPlayerChange = 'Y';
            } else if (rbtnFinalChoiceNo.isSelected()) {
                willPlayerChange = 'N';
            } else {
                java.util.Random rng = new java.util.Random();
                char variants[] = {'Y', 'N'};
                willPlayerChange =  variants[rng.nextInt(2)];
            }}
            
            // Determine final choise
            char simulatedFinalChoice;
            {
            if (willPlayerChange == 'Y') {// players changes choice            
                simulatedFinalChoice = "ABC".replace(String.valueOf(simulatedHostOpens), "").replace(String.valueOf(simulatedPlayerChoice), "").charAt(0);
            } else {// players choice remains the same
                simulatedFinalChoice = simulatedPlayerChoice;        
            }}
            
            // if player won the car increase the counter
            if (simulatedFinalChoice == simulatedCarPosition)
                playerWonCar++;     

        }
        
        // This is fake "simulation process" made with timer delay only for smoother user expirience
        // at the end it adds stats
        
        final int playerWonCarFinal = playerWonCar;
        final int simulationsNumberFinal = simulationsNumber;
        String willPlayerChangeStats;
        {
        if  (rbtnFinalChoiceYes.isSelected()) {
            willPlayerChangeStats = "Ja;       ";
        } else if (rbtnFinalChoiceNo.isSelected()) {
            willPlayerChangeStats = "Nej;     ";
        } else {
            willPlayerChangeStats = "Slump;";
        }}
        String playerChoiceStats;
        {
        if  (rbtnFirstChoiceA.isSelected())
            playerChoiceStats = "A;        ";
        else if (rbtnFirstChoiceB.isSelected()) 
            playerChoiceStats = "B;        ";
        else if (rbtnFirstChoiceC.isSelected()) 
            playerChoiceStats = "C;        ";
        else
            playerChoiceStats = "Slump;";
        }
        
        javax.swing.Timer timer = new javax.swing.Timer(1, new java.awt.event.ActionListener() {
            int i = 1;
            int totalIterations = 40;
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                    if (i <= totalIterations) {
                        // Update progress bar
                        int percentComplete = (i * 100) / totalIterations;
                        pgbProgress.setValue(percentComplete);                     
                        i++;
                    } else {
                        
                        ((javax.swing.Timer) e.getSource()).stop();  // Stop the timer after all iterations
                        
                        // Add simulation stats
                        javax.swing.text.StyledDocument doc = txpSimulationResults.getStyledDocument();
                        try {
                            javax.swing.text.SimpleAttributeSet bold = new javax.swing.text.SimpleAttributeSet();
                            javax.swing.text.StyleConstants.setBold(bold, true);
                            
                            doc.insertString(doc.getLength(), "Gardin: ", null);
                            doc.insertString(doc.getLength(), playerChoiceStats, bold);
                            doc.insertString(doc.getLength(), " Ändrade: ", null);
                            doc.insertString(doc.getLength(), willPlayerChangeStats, bold);
                            doc.insertString(doc.getLength(), " Bil: " + playerWonCarFinal + "/" + simulationsNumberFinal + "   ", null);
                            doc.insertString(doc.getLength(), String.format("%.2f", (playerWonCarFinal * 100.0 / simulationsNumberFinal)) + "%\n", bold);
                            
                        } catch (javax.swing.text.BadLocationException ex) {
                            ex.printStackTrace();
                        }
                        
                        // enable the button and controls
                        btnStartSimulation.setEnabled(true);  
                        setPanelEnabled(pnlFirstChoice, true);
                        setPanelEnabled(pnlFinalChoice, true);
                        setPanelEnabled(pnlSimulationsNumber, true);
                    }
            }
        });
        timer.start(); 
    }//GEN-LAST:event_btnStartSimulationActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /**
    *      *** My Functions ***
    */
    
    // This is filter for txfSimulationsNumber text field.
    // The purpoise is to let user fill in only digits and only up to maximum amount     
    class NumericDocumentFilter extends javax.swing.text.DocumentFilter {
        
        private int maxLength;

        public NumericDocumentFilter(int maxLength) {
            this.maxLength = maxLength;
        }        

        @Override
        public void insertString(FilterBypass fb, int offset, String string, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
            if ((fb.getDocument().getLength() + string.length()) <= maxLength && string.matches("\\d+")) {
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs) throws javax.swing.text.BadLocationException {
            if ((fb.getDocument().getLength() - length + text.length()) <= maxLength && text.matches("\\d+")) {
                super.replace(fb, offset, length, text, attrs);
            }
        }
    }
    

    // Function that disalbles buttons
    private void disableCurtains() {
        btnCurtainAEnabled = false;
        btnCurtainA.setFocusable(false);
        btnCurtainBEnabled = false;
        btnCurtainB.setFocusable(false);
        btnCurtainCEnabled = false;
        btnCurtainC.setFocusable(false);
    }    
    
    
    // Function that iterates through all panel components and sets enabled status for them
    public void setPanelEnabled(javax.swing.JPanel panel, boolean isEnabled) {
        for (java.awt.Component component : panel.getComponents()) {
            component.setEnabled(isEnabled);
        }
    }
    
    
    // Function that rangomly determins position of the car. Returnes name of the curtain.
    private char getCarPosition(){
        java.util.Random rng = new java.util.Random();
        char variants[] = {'A', 'B', 'C'};
        return variants[rng.nextInt(3)];
    }
    
    
    // Function that plays animation of car or goat reveal
    // Args: name of the curtain,
    private void curtainReveal(char btnName) {       
        
        javax.swing.Timer timer = new javax.swing.Timer(700, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                javax.swing.JButton btn = new javax.swing.JButton();

                switch (btnName) {
                    case 'A':
                        btn = btnCurtainA;
                        break;
                    case 'B':
                        btn = btnCurtainB;
                        break;
                    case 'C':
                        btn = btnCurtainC;
                        break;
                }           
                if (carPosition == btnName){
                    carGif.getImage().flush(); // Explicitly flush image data so gif can play again
                    btn.setIcon(carGif); // Set new icon
                } else {
                    goatGif.getImage().flush(); // Explicitly flush image data
                    btn.setIcon(goatGif); // Set new icon
                }
                
            }
        });
        timer.setRepeats(false);
        timer.start(); // start the timer       

    }
    
    
    // Function that shows arrow pointing player choice. 
    // Args: button (curtain)
    private void showChoiceArrow(char btnName) {
        switch (btnName) {
            case 'A':
                lblPlayerChoiceA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/Check.png")));
                lblPlayerChoiceB.setIcon(null); // Delete arrows under other curtains
                lblPlayerChoiceC.setIcon(null);
                break;
            case 'B':
                lblPlayerChoiceA.setIcon(null);
                lblPlayerChoiceB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/Check.png")));
                lblPlayerChoiceC.setIcon(null);
                break;
            case 'C':
                lblPlayerChoiceA.setIcon(null);
                lblPlayerChoiceB.setIcon(null);
                lblPlayerChoiceC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Uppgift/Check.png")));
                break;
        }
    }
    
    
    // Function that finds a goat to be revealed by the host after mlayer made first choice
    private char findGoat(char playerChoice, char carPosition) {
        char goatPosition;
        if (playerChoice != carPosition) { 
            // if player have chosen a goat
            // return curtain with the other goat
            goatPosition = "ABC".replace(String.valueOf(carPosition), "").replace(String.valueOf(playerChoice), "").charAt(0);
        } else { 
            // if player have chosen the car
            // choose one of remaining goats at random
            java.util.Random rng = new java.util.Random();
            goatPosition = "ABC".replace(String.valueOf(playerChoice), "").charAt(rng.nextInt(2));
        }
        return goatPosition;
    }
    

    /** Function that is activated after player has chosen the curtain:
    *   The host announces player choice
    *   He opens curtain with the goat
    *   He suggests a change of choice
    *   Buttons Yes / No appear
    *   Function returnes which curtain (with goat) the host has opened
    */  
    private char firstPlayerChoice(char playerChoice) {
        // Indicate player choice by showing an arrow
        showChoiceArrow(playerChoice);      
        
        // find cutrain to reveal a goat
        char curtainToOpen = findGoat(playerChoice, carPosition);
       
        // the host declares player choice and that he is goeing to reveal a goat
        txpHostText.setText(
                "Spelaren har valt gardin " + playerChoice + 
                "! Nu kommer jag att avslöja att det inte finns vinsten bakom gardinen " + curtainToOpen +
                "!"
        );
        
        // reveal the goat
        curtainReveal(curtainToOpen);       
       
        // after a pause the host questions if the player wnts to change his choice, buttons yes/no appear
        javax.swing.Timer timer2 = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            
                char curtainLeft = "ABC".replace(String.valueOf(curtainToOpen), "").replace(String.valueOf(playerChoice), "").charAt(0);
                
                txpHostText.setText(
                "<html>Vill du byta ditt val från gardin " + playerChoice + 
                " till gardin " + curtainLeft + "?"
                );
                
                javax.swing.SwingUtilities.invokeLater(() -> { // make sure update of button visibility happens after timer finishes
                    btnYes.setVisible(true);
                    btnYes.setFocusable(true);
                    btnYes.revalidate();
                    btnYes.repaint();

                    btnNo.setVisible(true);
                    btnNo.setFocusable(true);
                    btnNo.revalidate();
                    btnNo.repaint();

                    pnlGame.revalidate();
                    pnlGame.repaint();
                });
            }
        });
        timer2.setRepeats(false);
        timer2.start(); // Start the timer 
        
        return curtainToOpen;
    }
    
    
    /** Function that is activated after player has chosen if he is sure:
    *   All the curtains open
    *   The host announses what the player won
    *   Results of the game are added to stats field
    *   Button Play Again is enabled
    */ 
    private void secondPlayerChoice(String choice) {
        
        if (choice.equals("Yes")) {// players changes choice
            
            finalChoice = "ABC".replace(String.valueOf(hostOpened), "").replace(String.valueOf(playerChoice), "").charAt(0);
        
            btnYes.setBorder(javax.swing.BorderFactory.createCompoundBorder( //hihglite player choice
                javax.swing.BorderFactory.createLineBorder(new Color(255, 215, 0), 4),
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
            ));
            
        } else if (choice.equals("No")) {// players choice remains the same
            
            finalChoice = playerChoice;
            btnNo.setBorder(javax.swing.BorderFactory.createCompoundBorder( //hihglite player choice
                javax.swing.BorderFactory.createLineBorder(new Color(255, 215, 0), 4),
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
            ));           
        }        
        
        // update player choice pointer
        showChoiceArrow(finalChoice);        
        
        // reveal what player has won
        curtainReveal(finalChoice);        
        curtainReveal("ABC".replace(String.valueOf(hostOpened), "").replace(String.valueOf(finalChoice), "").charAt(0)); 
        
        // disable buttons
        btnYes.setEnabled(false);
        btnNo.setEnabled(false);
        
        String playerPrize = finalChoice == carPosition ? "bil" : "get";
        
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                // append result of this round
                txaResults.append(
                        "Första valet: " + playerChoice +
                        ", ändrade valet: " + (choice.equals("Yes") ? "Ja " : "Nej") +
                        ", vinst: en " + playerPrize + "\n"
                );                
            }
        });
        timer.setRepeats(false);
        timer.start(); // start the timer
        
        // announce what the player has won (in bold)
        javax.swing.text.StyledDocument doc = txpHostText.getStyledDocument();
        try {
            javax.swing.text.SimpleAttributeSet bold = new javax.swing.text.SimpleAttributeSet();
            javax.swing.text.StyleConstants.setBold(bold, true);
            doc.insertString(doc.getLength(), "\nSpelaren har vunnit en " + playerPrize + "!", bold);
        } catch (javax.swing.text.BadLocationException e) {
            e.printStackTrace();
        }
        
        //update of button visibility
        javax.swing.SwingUtilities.invokeLater(() -> { 
            btnYes.setVisible(true);
            btnYes.setFocusable(true);
            btnYes.revalidate();
            btnYes.repaint();

            btnNo.setVisible(true);
            btnNo.setFocusable(true);
            btnNo.revalidate();
            btnNo.repaint();

            pnlGame.revalidate();
            pnlGame.repaint();
        });
        
        // Now game can be reset
        btnPlayAgain.setEnabled(true);
        
    }
    
    /**
    *      *** MAIN ***
    */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Uppgift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Uppgift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Uppgift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Uppgift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Uppgift().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurtainA;
    private javax.swing.JButton btnCurtainB;
    private javax.swing.JButton btnCurtainC;
    private javax.swing.ButtonGroup btnGroupFinalChoice;
    private javax.swing.ButtonGroup btnGroupFirstChoice;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnStartSimulation;
    private javax.swing.JButton btnYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblFinalChoice;
    private javax.swing.JLabel lblFirstChoice;
    private javax.swing.JLabel lblGameHost;
    private javax.swing.JLabel lblGameTitle;
    private javax.swing.JLabel lblIntroduction;
    private javax.swing.JLabel lblPlayerChoiceA;
    private javax.swing.JLabel lblPlayerChoiceB;
    private javax.swing.JLabel lblPlayerChoiceC;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblSimulationResults;
    private javax.swing.JLabel lblSimulationsNumber;
    private javax.swing.JProgressBar pgbProgress;
    private javax.swing.JPanel pnlFinalChoice;
    private javax.swing.JPanel pnlFirstChoice;
    private javax.swing.JPanel pnlGame;
    private javax.swing.JPanel pnlSimulation;
    private javax.swing.JPanel pnlSimulationsNumber;
    private javax.swing.JRadioButton rbtnFinalChoiceNo;
    private javax.swing.JRadioButton rbtnFinalChoiceRandom;
    private javax.swing.JRadioButton rbtnFinalChoiceYes;
    private javax.swing.JRadioButton rbtnFirstChoiceA;
    private javax.swing.JRadioButton rbtnFirstChoiceB;
    private javax.swing.JRadioButton rbtnFirstChoiceC;
    private javax.swing.JRadioButton rbtnFirstChoiceRandom;
    private javax.swing.JScrollPane scrSimulationResults;
    private javax.swing.JTabbedPane tbpMainTabs;
    private javax.swing.JTextArea txaResults;
    private javax.swing.JTextField txfSimulationsNumber;
    private javax.swing.JTextPane txpHostText;
    private javax.swing.JTextPane txpSimulationResults;
    // End of variables declaration//GEN-END:variables
}

